# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_threshold_cpp <- function(B, lambda) {
    .Call(`_IMR_soft_threshold_cpp`, B, lambda)
}

row_means_cpp <- function(yS4, n_cols) {
    .Call(`_IMR_row_means_cpp`, yS4, n_cols)
}

col_means_cpp <- function(yS4, n_rows) {
    .Call(`_IMR_col_means_cpp`, yS4, n_rows)
}

add_to_rows_inplace_cpp <- function(yx, i, add_per_row, alpha = 1.0) {
    invisible(.Call(`_IMR_add_to_rows_inplace_cpp`, yx, i, add_per_row, alpha))
}

add_to_cols_inplace_cpp <- function(yx, p, add_per_col, alpha = 1.0) {
    invisible(.Call(`_IMR_add_to_cols_inplace_cpp`, yx, p, add_per_col, alpha))
}

frob_ratio_cpp <- function(Uold, Dsqold, Vold, U, Dsq, V) {
    .Call(`_IMR_frob_ratio_cpp`, Uold, Dsqold, Vold, U, Dsq, V)
}

update_A_cpp <- function(yS4, V, U, Dsq, lambda_M) {
    .Call(`_IMR_update_A_cpp`, yS4, V, U, Dsq, lambda_M)
}

update_B_cpp <- function(yS4, U, V, Dsq, lambda_M) {
    .Call(`_IMR_update_B_cpp`, yS4, U, V, Dsq, lambda_M)
}

partial_crossprod <- function(u, v, irow, pcol, vtranspose = FALSE) {
    .Call(`_IMR_partial_crossprod`, u, v, irow, pcol, vtranspose)
}

svd_small_nc_cpp <- function(mS) {
    .Call(`_IMR_svd_small_nc_cpp`, mS)
}

svd_small_nr_cpp <- function(mS) {
    .Call(`_IMR_svd_small_nr_cpp`, mS)
}

