// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// svd_small_nc_cpp
Rcpp::List svd_small_nc_cpp(SEXP mS);
RcppExport SEXP _IMR_svd_small_nc_cpp(SEXP mSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mS(mSSEXP);
    rcpp_result_gen = Rcpp::wrap(svd_small_nc_cpp(mS));
    return rcpp_result_gen;
END_RCPP
}
// svd_small_nr_cpp
Rcpp::List svd_small_nr_cpp(SEXP mS);
RcppExport SEXP _IMR_svd_small_nr_cpp(SEXP mSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mS(mSSEXP);
    rcpp_result_gen = Rcpp::wrap(svd_small_nr_cpp(mS));
    return rcpp_result_gen;
END_RCPP
}
