#' Prepare Data and Model Structure for IMR
#'
#' @description
#' `imr_data` creates a structured data object for Incomplete Matrix Regression (IMR).
#' It handles target matrix formatting, optional train/validation splitting,
#'  QR decomposition of covariates, and initializes a default model structure
#'  based on the provided inputs.
#'
#' @param Y A numeric matrix (dense or sparse) representing the target/response
#' matrix. This is the only required parameter.
#' Missing values and Zeros are treated as unobserved.
#' @param X A numeric matrix of row covariates. Must have the same number of rows as `Y`.
#'   Defaults to `NULL`.
#' @param Z A numeric matrix of column covariates. Must have the same number of columns
#'   as `Y`. Defaults to `NULL`.
#' @param similarity_rows A list containing the eigenvalues (`d`) and eigenvectors (`U`)
#'   of the row similarity matrix, generated by \code{\link{imr_similarity}}.
#'   Defaults to `NULL`.
#' @param similarity_cols A list containing the eigenvalues (`d`) and eigenvectors (`U`)
#'   of the column similarity matrix, generated by \code{\link{imr_similarity}}.
#'   Defaults to `NULL`.
#' @param val_prop Numeric. The proportion of observed entries in `Y` to hold out for
#'   validation. If `0.0` (the default), no validation split is performed. Validation is required
#'   for hyperparameter tuning.
#' @param seed Integer. An optional random seed for reproducibility when creating the
#'   train/validation split. Defaults to `NULL`.
#'
#' @details
#' By default, `imr_data` assumes that if you provide `X`, `Z`, or similarity matrices,
#' you want to include them in your IMR model. It sets `$model` logical
#' flags to `TRUE` for any provided data. If you wish to change this model structure
#' later without re-processing the data matrices, use the `update()` method.
#'
#' @return An object of class `"imr_data"`, containing:
#' \itemize{
#'   \item \code{Y}, \code{y_train}, \code{y_valid}: The target matrix and its
#'   splits (as `Incomplete` objects).
#'   \item \code{Xq}, \code{Xr}, \code{Zq}, \code{Zr}: The QR decompositions of
#'   the covariates.
#'   \item \code{similarity_rows}, \code{similarity_cols}: The provided similarity
#'   matrices.
#'   \item \code{meta}: A list of dataset dimensions, sparsity, and variable counts.
#'   \item \code{model}: A list of logical flags defining the current model structure.
#' }
#'
#' @seealso [update.imr_data()], [imr_similarity()]
#' @export
#'
#' @examples
#'
#' # create sample data
#' Y <- matrix(
#'   c(2, NA, 3,
#'   4, .5, NA,
#'   NA, NA, 5), 3, byrow= TRUE
#' )
#'
#' # create covariate matrix of 2 variables
#' X <- matrix(rnorm(3*2), 3, 2)
#'
#' # create the data object
#' data <- imr_data(Y =  Y, X = X, val_prop = 0.0)
#'
#' # update the model to add row intercepts
#' data <- update(data, row_intercept = TRUE)
#'
#' # print the metadata
#' print(data)
#'
imr_data <- function(Y,
                     X = NULL,
                     Z = NULL,
                     similarity_rows = NULL,
                     similarity_cols = NULL,
                     val_prop = 0.0,
                     seed = NULL) {
  out <- list()
  if (!is.null(seed) && is.numeric(seed)) set.seed(seed)

  # ---  Target Matrix Setup ---
  out$Y <- Y <- as.Incomplete(Y)
  out$Y@x <- out$Y@x + 0 # this is to force a copy
  obs_mask <- as.matrix(Y != 0)

  dims <- dim(Y)
  n_total_obs <- sum(obs_mask)

  # --- Train/Validation Split ---
  split_data <- is.numeric(val_prop) && val_prop > 0

  if (split_data) {
    message("Performing train/valid split...")

    valid_mask_mat <- mask_train_test_split(obs_mask, val_prop, seed)
    train_mask_mat <- obs_mask * (1 - valid_mask_mat)

    out$valid_mask <- as.Incomplete(valid_mask_mat)
    out$y_train <- as.Incomplete(Y * train_mask_mat)
    out$y_valid <- as.Incomplete(Y * valid_mask_mat)

    n_train <- sum(train_mask_mat)
    n_valid <- sum(valid_mask_mat)
  } else {
    n_train <- n_total_obs
    n_valid <- 0
  }

  out$obs_mask <- as.Incomplete(obs_mask * 1)

  # ---  Similarity Matrices ---
  stopifnot(is.null(similarity_rows) || inherits(similarity_rows, "imr_similarity"))
  stopifnot(is.null(similarity_cols) || inherits(similarity_cols, "imr_similarity"))
  out$similarity_rows <- similarity_rows
  out$similarity_cols <- similarity_cols

  # ---  Covariates ---
  if (!is.null(X)) {
    stopifnot(is.matrix(X), nrow(X) == nrow(Y))
    xqr <- qr(X)
    out$Xq <- qr.Q(xqr)
    colnames(out$Xq) <- colnames(X)
    out$Xr <- qr.R(xqr)
  }

  if (!is.null(Z)) {
    stopifnot(is.matrix(Z), nrow(Z) == ncol(Y))
    Zqr <- qr(Z)
    out$Zq <- qr.Q(Zqr)
    colnames(out$Zq) <- colnames(Z)
    out$Zr <- qr.R(Zqr)
  }

  # ---  Metadata  ---
  out$meta <- list(
    dimensions = dims,
    sparsity = 1 - (n_total_obs / (dims[1] * dims[2])),
    total_obs = n_total_obs,
    split_data = split_data,
    n_train = n_train,
    n_valid = n_valid,
    val_prop = if (split_data) val_prop else 0,
    has_X = !is.null(X),
    num_X_vars = if (!is.null(X)) ncol(X) else 0,
    names_X_vars = if (!is.null(X)) colnames(X) else NULL,
    has_Z = !is.null(Z),
    num_Z_vars = if (!is.null(Z)) ncol(Z) else 0,
    names_Z_vars = if (!is.null(Z)) colnames(Z) else NULL,
    has_sim_row = !is.null(out$similarity_rows),
    has_sim_col = !is.null(out$similarity_cols)
  )
  # --- Model Structure ----
  out$model <- list(
    row_covariates = out$meta$has_X,
    col_covariates = out$meta$has_Z,
    low_rank_component = TRUE,
    row_similarity = out$meta$has_sim_row,
    col_similarity = out$meta$has_sim_col,
    row_intercept = FALSE,
    col_intercept = FALSE,
    shared_beta = FALSE,
    shared_gamma = FALSE
  )

  structure(out, class = "imr_data")
}
#----------------------------------------
#' Update IMR Model Structure
#'
#' @description
#' Updates the logical model structure of an existing `"imr_data"` object. This allows
#' you to toggle model components (like intercepts, covariates, or low-rank components)
#' on or off without needing to re-process the underlying data matrices.
#'
#' @param object An object of class `"imr_data"`.
#' @param row_covariates Logical. Include row covariates in the model?
#'   (Requires `X` to have been provided to `imr_data`).
#' @param col_covariates Logical. Include column covariates in the model?
#'   (Requires `Z` to have been provided to `imr_data`).
#' @param low_rank_component Logical. Include the low-rank component (\eqn{M=U D V^T})?
#' @param row_similarity Logical. Include row similarity penalties?
#'   (Requires `similarity_rows` to have been provided to `imr_data`).
#' @param col_similarity Logical. Include column similarity penalties?
#'   (Requires `similarity_cols` to have been provided to `imr_data`).
#' @param row_intercept Logical. Include a row intercept/bias term?
#' @param col_intercept Logical. Include a column intercept/bias term?
#' @param shared_beta Logical. Should row covariate effects (`beta`) be shared
#'   across all columns?
#' @param shared_gamma Logical. Should column covariate effects (`gamma`) be shared
#'   across all rows?
#' @param ... Additional arguments (ignored).
#'
#' @return The modified `"imr_data"` object with updated `$model` flags.
#'
#' @seealso [imr_data()], [imr_similarity()]
#'
#' @inherit imr_data examples
#'
#' @export
#' @method update imr_data
update.imr_data <- function(object,
                            row_covariates = NULL,
                            col_covariates = NULL,
                            low_rank_component = NULL,
                            row_similarity = NULL,
                            col_similarity = NULL,
                            row_intercept = NULL,
                            col_intercept = NULL,
                            shared_beta = NULL,
                            shared_gamma = NULL,
                            ...) {
  update_flag <- function(obj, flag_val, flag_name, dependency_name) {
    if (!is.null(flag_val)) {
      # Ensure it's a single boolean
      flag_val <- as.logical(flag_val[1])

      if (flag_val && !obj$meta[[dependency_name]]) {
        stop(sprintf(
          "Cannot set '%s = TRUE' because the underlying data ('%s') was not provided.",
          flag_name, dependency_name
        ), call. = FALSE)
      }
      obj$model[[flag_name]] <- flag_val
    }
    return(obj)
  }

  object <- update_flag(object, row_covariates, "row_covariates", "has_X")
  object <- update_flag(object, col_covariates, "col_covariates", "has_Z")
  object <- update_flag(object, row_similarity, "row_similarity", "has_sim_row")
  object <- update_flag(object, col_similarity, "col_similarity", "has_sim_col")

  toggle <- function(obj, val, name) {
    if (!is.null(val)) obj$model[[name]] <- as.logical(val[1])
    return(obj)
  }

  object <- toggle(object, low_rank_component, "low_rank_component")
  object <- toggle(object, row_intercept, "row_intercept")
  object <- toggle(object, col_intercept, "col_intercept")

  if (!is.null(shared_beta)) {
    if (shared_beta && !object$model$row_covariates) {
      warning("Setting shared_beta = TRUE does nothing if row covariates are inactive.")
    }
    object$model$shared_beta <- as.logical(shared_beta[1])
  }

  if (!is.null(shared_gamma)) {
    if (shared_gamma && !object$model$col_covariates) {
      warning("Setting shared_gamma = TRUE does nothing if col covariates are inactive.")
    }
    object$model$shared_gamma <- as.logical(shared_gamma[1])
  }

  return(object)
}

#' @title Summary of data and model structure
#' @param x An `imr_data` object
#' @param ... Additional arguments to comply with generic function
#' @seealso [imr_data()] [update.imr_data()] [imr_similarity()]
#' @inherit imr_data examples
#' @export
#' @method print imr_data
print.imr_data <- function(x, ...) {
  m <- x$meta # What data is available in memory
  a <- x$model # What the solver is instructed to use

  cat("\n== IMR Data Object ==\n")

  # --- 1. Base Dimensions ---
  cat(sprintf("Target Matrix (Y): %d rows x %d cols\n", m$dimensions[1], m$dimensions[2]))
  cat(sprintf("Observed Entries:  %d (%.2f%% Sparsity)\n", m$total_obs, m$sparsity * 100))

  # --- 2. Train/Valid Split info ---
  if (m$split_data) {
    cat(sprintf("  - Training:      %d (%.1f%%)\n", m$n_train, 100 * (1 - m$val_prop)))
    cat(sprintf("  - Validation:    %d (%.1f%%)\n", m$n_valid, 100 * m$val_prop))
  } else {
    cat("  - Training:      Using 100% of data (No validation split)\n")
  }

  # --- 3. Active Submodel Configuration ---
  cat("\n-- Model Configuration --\n")

  # Helper function to align text and format the active/inactive tags
  format_status <- function(has_data, is_active, data_desc, is_shared = NULL) {
    if (!has_data) {
      return(sprintf("[None]"))
    }
    status_tag <- if (is_active) "[ACTIVE]" else ""
    shared_tag <- ""
    if (!is.null(is_shared) && is_active) {
      shared_tag <- if (is_shared) " (Shared)" else " (Unshared)"
    }
    return(sprintf("%-15s %s%s", data_desc, status_tag, shared_tag))
  }

  # Low-rank is a purely algorithmic component (doesn't depend on external data)
  cat(sprintf(
    "%-20s:  %23s\n", "Low-Rank Matrix (M)",
    if (a$low_rank_component) "[ACTIVE]" else ""
  ))
  cat(sprintf("%-20s: %24s\n", "Row Intercepts", if (a$row_intercept) "[ACTIVE]" else ""))
  cat(sprintf("%-20s: %24s\n", "Col Intercepts", if (a$col_intercept) "[ACTIVE]" else ""))

  # Covariates
  cat(sprintf(
    "%-20s: %s\n", "Row Covariates (X)",
    format_status(
      m$has_X, a$row_covariates, sprintf("%d vars", m$num_X_vars),
      a$shared_beta
    )
  ))

  cat(sprintf(
    "%-20s: %s\n", "Col Covariates (Z)",
    format_status(
      m$has_Z, a$col_covariates, sprintf("%d vars", m$num_Z_vars),
      a$shared_gamma
    )
  ))

  # Similarities
  cat(sprintf(
    "%-20s: %s\n", "Row Similarity",
    format_status(m$has_sim_row, a$row_similarity, "Provided")
  ))

  cat(sprintf(
    "%-20s: %s\n", "Col Similarity",
    format_status(m$has_sim_col, a$col_similarity, "Provided")
  ))

  cat("==========================\n")
  invisible(x)
}


#' @title Reconstruct Model Estimates and Components
#'
#' @description
#' Calculates the estimated response matrix from a fitted IMR model. In addition
#' to the final predicted values, it computes and returns the individual structural
#' components of the model, such as the low-rank matrix, covariate effects, and intercepts.
#'
#' @param fit An object of class `"imr_fit"`, generated by \code{\link{imr_fit}}.
#' @param data An object of class `"imr_data"`, generated by \code{\link{imr_data}}.
#' @param trace Logical. If `TRUE` (the default), prints progress messages for
#'   each reconstruction step.
#'
#' @details
#' During the model fitting process, covariates are orthogonally transformed using
#' QR decomposition. The `reconstruct`
#' function reverses this process, using the `R` matrices (`Xr` and `Zr`) to
#' back-transform the estimated coefficients (`beta` and `gamma`) to the original
#' scale of the input data.
#'
#' The final `estimates` matrix is computed by summing the active components
#' based on the model structure: the low-rank matrix (\eqn{M = U D V^T}), row covariate
#' effects (\eqn{X \beta}), column covariate effects (\eqn{\Gamma Z}), and any intercepts.
#' The function automatically handles matrix dimension sweeping for shared vs.
#' unshared effects.
#'
#' @return A list containing the reconstructed components and final estimates:
#' \itemize{
#'   \item \code{beta}: The row covariate coefficients transformed back to the original scale.
#'   \item \code{gamma}: The column covariate coefficients transformed back to the original scale.
#'   \item \code{M}: The reconstructed low-rank component matrix.
#'   \item \code{xbeta}: The matrix of row covariate effects.
#'   \item \code{gammaz}: The matrix of column covariate effects.
#'   \item \code{beta0}: The estimated row intercepts.
#'   \item \code{gamma0}: The estimated column intercepts.
#'   \item \code{estimates}: The final predicted response matrix (the sum of all active components).
#' }
#'
#' @seealso [reconstruct_partial()]
#'
#' @examples
#' \dontrun{
#' # construct the data object
#' data <- imr_data(Y = Y, X = X)
#' # fit the model
#' fit <- imr_fit(data, lambda_beta = 0, rank = 3, lambda_m = 0.2)
#' # estimate the target matrix
#' target <- reconstruct(fit, data)$estimates
#' }
#'
#' @export
reconstruct <- function(fit, data, trace = TRUE) {
  stopifnot(inherits(fit, "imr_fit"))
  stopifnot(inherits(data, "imr_data"))

  out <- list(
    beta = NULL, gamma = NULL, M = NULL,
    beta0 = NULL, gamma0 = NULL,
    xbeta = NULL, gammaz = NULL, estimates = 0
  )

  coefs <- fit$coefficients
  meta <- fit$meta

  # Get dimensions to safely initialize estimates if M is absent
  n <- data$meta$dimensions[1]
  m <- data$meta$dimensions[2]
  out$estimates <- matrix(0, nrow = n, ncol = m)

  # --- reconstruct M ---
  if (!is.null(coefs$u) && !is.null(coefs$d) && !is.null(coefs$v)) {
    if (trace) message("Constructing M ...")
    out$M <- coefs$u %*% (coefs$d * t(coefs$v))
    out$estimates <- out$estimates + out$M
  }

  # --- Reconstructing row covariate effects ---
  if (!is.null(coefs$beta) && !is.null(data$Xq) && !is.null(data$Xr)) {
    if (trace) message("Constructing XBeta ...")

    # Back-transform beta to original scale
    out$beta <- solve(data$Xr, coefs$beta)
    out$xbeta <- data$Xq %*% coefs$beta

    if (meta$shared_effects["beta"]) {
      # Shared beta: xbeta is an n x 1 matrix
      out$estimates <- sweep(out$estimates, 1, as.vector(out$xbeta), "+")
    } else {
      # Unshared beta: xbeta is an n x m matrix.
      out$estimates <- out$estimates + out$xbeta
    }
  }

  # --- Reconstructing column covariate effects ---
  if (!is.null(coefs$gamma) && !is.null(data$Zq) && !is.null(data$Zr)) {
    if (trace) message("Constructing GammaZ ...")

    # Back-transform gamma to original scale
    out$gamma <- coefs$gamma %*% solve(t(data$Zr))
    out$gammaz <- coefs$gamma %*% t(data$Zq)

    if (meta$shared_effects["gamma"]) {
      # Shared gamma: gammaz is a 1 x m matrix.
      out$estimates <- sweep(out$estimates, 2, as.vector(out$gammaz), "+")
    } else {
      # Unshared gamma: gammaz is an n x m matrix.
      out$estimates <- out$estimates + out$gammaz
    }
  }

  # --- Adding Intercepts ---
  if (!is.null(coefs$beta0)) {
    if (trace) message("Constructing row intercepts ...")
    out$beta0 <- coefs$beta0
    out$estimates <- sweep(out$estimates, 1, as.vector(coefs$beta0), "+")
  }

  if (!is.null(coefs$gamma0)) {
    if (trace) message("Constructing column intercepts ...")
    out$gamma0 <- coefs$gamma0
    out$estimates <- sweep(out$estimates, 2, as.vector(coefs$gamma0), "+")
  }

  if (trace) message("done.")
  return(out)
}
#-----------------------------

#' Partially Reconstruct Model Estimates for Specific Indices
#'
#' @description
#' Computes the estimated response matrix from a fitted IMR model, but *only* for
#' a specific subset of matrix entries. This is highly memory-efficient and fast
#' when you only need to evaluate predictions on a test set or validation mask,
#' as it avoids computing the full dense prediction matrix.
#'
#' @param fit An object of class `"imr_fit"`, generated by \code{\link{imr_fit}}.
#' @param data An object of class `"imr_data"`generated by \code{\link{imr_data}}.
#' @param irow,pcol Objects of class `"integer` corresponding to the `@i` and `@p`
#'    slots in a `"CsparseMatrix` denoting the indices of the elements to be estimated.
#'    The returned object corresponds to the `x` slot of said object.
#' @param trace Logical. If `TRUE`, prints progress messages for each reconstruction
#'   step. Defaults to `FALSE`.
#' @param return_matrix Logical. If `TRUE` then it returns a `CsparseMatrix` with
#'    the following slots: `@i=irow`, `@p=pcol`, `@x=estimates`. If `FALSE`, only
#'    the `@x` slot is returned as a vector. Defaults to `FALSE`.
#'
#' @details
#' Unlike the full \code{\link{reconstruct}} function, which allocates and calculates
#' every cell of an \eqn{n \times m} matrix, `reconstruct_partial` relies on optimized C++
#' routines to calculate only the targeted entries.
#'
#' @return Either a `CsparseMatrix` object or a numeric vector (see above).
#'
#' @seealso [reconstruct()]
#'
#' @examples
#' \dontrun{
#' # construct the data object
#' data <- imr_data(Y = Y, X = X)
#' # fit the model
#' fit <- imr_fit(data, lambda_beta = 0, rank = 3, lambda_m = 0.2)
#' # compute estimates of the training data
#' estimates <- reconstruct_partial(fit, data, data$Y@i, data$Y@p, return_matrix = FALSE)
#' # compute the training Root Mean Squared Error
#' evaluate(estimates, data$Y@x, metric = "RMSE")
#' }
#' @export
reconstruct_partial <- function(fit, data, irow, pcol, trace = FALSE, return_matrix = FALSE) {
  stopifnot(inherits(fit, "imr_fit"))
  stopifnot(inherits(data, "imr_data"))

  coefs <- fit$coefficients
  meta <- fit$meta

  # --- Reconstruct M ---
  if (!is.null(coefs$u) && !is.null(coefs$d) && !is.null(coefs$v)) {
    if (trace) message("Constructing M ...")
    target <- partial_crossprod(
      coefs$u,
      sweep(t(coefs$v), 1, coefs$d, "*"),
      irow, pcol
    )
  } else {
    target <- rep(0.0, length(irow))
  }

  # --- reconstruct row covariate effects ---
  if (!is.null(coefs$beta) && !is.null(data$Xq)) {
    if (trace) message("Constructing XBeta ...")

    if (meta$shared_effects["beta"]) {
      xbeta_vec <- as.numeric(data$Xq %*% coefs$beta)
      add_to_rows_inplace_cpp(target, irow, xbeta_vec)
    } else {
      target <- target + partial_crossprod(data$Xq, coefs$beta, irow, pcol)
    }
  }

  # ---  Column covariate effects ---
  if (!is.null(coefs$gamma) && !is.null(data$Zq)) {
    if (trace) message("Constructing GammaZ ...")

    if (meta$shared_effects["gamma"]) {
      gammaz_vec <- as.numeric(coefs$gamma %*% t(data$Zq))
      add_to_cols_inplace_cpp(target, pcol, gammaz_vec)
    } else {
      target <- target + partial_crossprod(coefs$gamma, data$Zq, irow, pcol, vtranspose = TRUE)
    }
  }

  # ---  Intercepts ---
  if (!is.null(coefs$beta0)) {
    if (trace) message("Constructing row intercepts ...")
    add_to_rows_inplace_cpp(target, irow, coefs$beta0)
  }

  if (!is.null(coefs$gamma0)) {
    if (trace) message("Constructing column intercepts ...")
    add_to_cols_inplace_cpp(target, pcol, coefs$gamma0)
  }

  if(return_matrix)
    target <- new("imr_incomplete",
                  i = irow,
                  p = pcol,
                  x = target,
                  Dim = fit$meta_data$dimensions)

  return(target)
}

#----------------------------------------------------------------

#' @title Generate Similarity or Information Matrix Object
#'
#' @description
#' Creates an `"imr_similarity"` object containing the Eigenvalue-decomposition of a
#' similarity or information matrix. This object is required for incorporating
#' row or column similarities in an IMR model. The function can accept a
#' pre-computed matrix or generate a covariance matrix from distance data using
#' specified kernels.
#'
#' @param x Either a square numeric matrix, or a character string specifying a
#'   kernel method (`"matern"` or `"rbf"`). If a matrix is provided, it should
#'   be a similarity or information matrix (if `invert = FALSE`), or a covariance
#'   matrix (if `invert = TRUE`).
#' @param d A numeric distance matrix. This is strictly required if `x` is set to
#'   `"matern"` or `"rbf"`. Defaults to `NULL`.
#' @param matern_smoothness,matern_range  the parameters for the Matern kernel:
#'   `smoothness` and `range`. Defaults to `(smoothness = 1.5, range = 1)`.
#' @param rbf_ell The length-scale parameter for the Radial Basis Function
#'   (RBF) kernel. Defaults to `1`.
#' @param jitter Numeric. A small positive value added to the diagonal of the
#'   matrix to improve numerical stability and reduce the condition number.
#'   This is applied before any inversion. Defaults to `0`.
#' @param invert Logical. Should the matrix be inverted? The IMR model
#'   expects an information matrix. If your input (or generated kernel)
#'   represents a covariance matrix, you must set this to `TRUE` to invert it.
#'   Defaults to `FALSE`.
#'
#' @return An object of class `"imr_similarity"`. This is a list containing:
#' \itemize{
#'   \item \code{U}: A matrix of eigenvectors.
#'   \item \code{d}: A vector of absolute eigenvalues.
#'   \item \code{meta}: A list of metadata.
#' }
#' @seealso [imr_data()], [print.imr_similarity()]
#'
#' @examples
#' # generate 5 random spatial locations
#' coords <- data.frame(
#' x = runif(5, 0, 10),
#' y = runif(5, 0 , 10))
#'
#' # compute the distance matrix
#' distance_matrix <- as.matrix(dist(coords))
#'
#' # generate the similarity object of a 5/2 matern kernel
#' sim <- imr_similarity("matern", distance_matrix, matern_smoothness = 1.5, invert = TRUE)
#'
#' # print the matrix's metadata
#' print(sim)
#'
#' @export
imr_similarity <- function(x,
                           d = NULL,
                           matern_smoothness = 1.5,
                           matern_range = 1,
                           rbf_ell = 1,
                           jitter = 0,
                           invert = FALSE) {
  S <- NULL
  source_type <- "User Matrix"
  params_used <- list()

  if (is.matrix(x)) {
    if (nrow(x) != ncol(x)) stop("Input matrix 'x' must be square.")
    S <- x
  } else if (is.character(x)) {
    if (is.null(d)) stop("Distance matrix 'd' is required for kernel generation.")

    if (tolower(x) == "matern") {
      source_type <- "Matern Kernel"
      params_used <- c(smoothness = matern_smoothness,
                       range      = matern_range)

      S <- fields::Matern(d,
        smoothness = matern_smoothness,
        range = matern_range
      )
    } else if (tolower(x) == "rbf") {
      source_type <- "RBF Kernel"
      params_used <- c(ell = rbf_ell)
      ell <- rbf_ell
      S <- exp(-(d^2) / (2 * ell^2))
    } else {
      stop("Unknown method. 'x' must be a matrix, 'matern', or 'RBF'.")
    }
    if (!invert) {
      warning(paste(
        "Generated a raw Covariance matrix without inversion.",
        "fit_imr() expects the inverse."
      ))
    }
  } else {
    stop("Input 'x' must be a matrix or a character string ('matern', 'RBF').")
  }

  if (is.numeric(jitter) && jitter > 0) {
    S <- S + diag(jitter, nrow(S), ncol(S))
    # source_type <- paste(source_type, "(With Jitter)")
  } else {
    jitter <- 0
  }

  if (invert) {
    S <- inv(S)
    source_type <- paste(source_type, "(Inverted)")
  }


  decomp <- eigen(S, symmetric = TRUE)
  evals <- abs(decomp$values)
  cond_num <- max(evals) / min(evals[evals > 0])

  structure(
    list(
      U = decomp$vectors,
      d = decomp$values,
      meta = list(
        source = source_type,
        dim = dim(S),
        params = params_used,
        inverted = invert,
        jitter = jitter,
        condition_number = cond_num
      )
    ),
    class = "imr_similarity"
  )
}


#' @title Summary of the similarity matrix
#' @param x An `imr_similarity` object
#' @param ... Additional arguments to comply with generic function
#' @seealso [imr_similarity()]
#' @inherit imr_similarity examples
#' @export
#' @method print imr_similarity
print.imr_similarity <- function(x, ...) {
  cat("\n== IMR Similarity Decomposition ==\n")
  cat(sprintf("Source:           %s\n", x$meta$source))
  cat(sprintf("Dimensions:       %d x %d\n", x$meta$dim[1], x$meta$dim[2]))
  cat(sprintf("Jitter value:     %s\n", x$meta$jitter))

  if (length(x$meta$params) > 0) {
    p_names <- names(x$meta$params)
    p_vals <- unlist(x$meta$params)
    cat(sprintf("Parameters:       %s\n", paste(p_names, p_vals, sep = "=", collapse = ", ")))
  }
  cond_fmt <- if (x$meta$condition_number > 1e4) "%.2e" else "%.2f"
  cat(sprintf("Condition Number: %s\n", sprintf(cond_fmt, x$meta$condition_number)))

  cat("Top 5 Eigenvalues:", paste(format(head(x$d, 5), digits = 3), collapse = ", "), "...\n")
  cat("==================================\n")

  invisible(x)
}
