#' Control Parameters for IMR Convergence
#'
#' @description
#' Defines and creates a structure for the convergence parameters used by the
#' IMR fit function.
#'
#' @param maxit Integer. The maximum number of iterations allowed for the fit
#'   function. Defaults to `600`.
#' @param thresh Numeric. The convergence threshold. Training stops early if
#'   the Frobenius difference between the new and old parameters falls below
#'   this value. Defaults to `1e-5`.
#' @param trace Logical. If `TRUE`, prints the Frobenius ratio and the loss
#'   function value at each iteration. Defaults to `FALSE`.
#' @param ls_initial Logical. If `TRUE` (the default), least-squares initial
#'   values are used. If `FALSE`, random initialization is used. It is
#'   recommended to leave this as `TRUE` to speed up convergence.
#'
#' @return An object of class `"imr_convergence"`, which is a list containing
#'   the specified control parameters.
#' @seealso [imr_fit()], [print.imr_convergence()]
#' @export
#'
#' @examples
#' # Use the default convergence parameters
#' convergence <- imr_convergence()
#' print(convergence)
#'
imr_convergence <- function(maxit = 600,
                            thresh = 1e-5,
                            trace = FALSE,
                            ls_initial = TRUE) {
  structure(
    list(
      maxit = maxit,
      thresh = thresh,
      trace = trace,
      ls_initial = ls_initial
    ),
    class = "imr_convergence"
  )
}

#' Fit an IMR Model
#'
#' @description
#' The main function for fitting an Incomplete Matrix Regression (IMR) model.
#' It takes a prepared `imr_data` object and estimates the parameters based on the
#' specified model structure and regularization parameters.
#'
#' @param data An object of class `"imr_data"`. This object contains the response
#'   matrix, optional covariates and similarities, and the specific model structure to be fitted.
#' @param rank Integer. The rank of the low-rank component (\eqn{M=U D V^T}). This is
#'   required if the model structure includes a low-rank component. Defaults to `2`.
#' @param lambda_m Numeric. The regularization parameter for the low-rank component.
#'   Required if the low-rank component is included in the model. Defaults to `0`.
#' @param lambda_beta Numeric. The regularization parameter for the row covariates.
#'   Only used if row covariates are specified in the `imr_data` model structure.
#'   Defaults to `0`.
#' @param lambda_gamma Numeric. The regularization parameter for the column covariates.
#'   Only used if column covariates are specified in the `imr_data` model structure.
#'   Defaults to `0`.
#' @param convergence An object of class `"imr_convergence"`, generated by
#'   `imr_convergence()`. It dictates the maximum iterations, threshold, tracing,
#'   and initialization method.
#' @param warm_start An optional object of class `"imr_fit"`. If provided, the
#'   coefficients from this previous fit are used as the starting values for the
#'   new optimization, overriding the initialization strategy in `convergence`.
#'   Defaults to `NULL`.
#' @param training Logical. If `TRUE`, the model fits on `data$y_train` rather than
#'   the full `data$Y` matrix. This is primarily intended for internal use during
#'   cross-validation. Generally, users should leave this as `FALSE`. Defaults to `FALSE`.
#'
#' @return An object of class `"imr_fit"`. This is a list containing:
#' \itemize{
#'   \item \code{coefficients}: A list of the estimated model parameters, which may include
#'         the low-rank matrices (\code{u}, \code{d}, \code{v}), covariate effects
#'         (\code{beta}, \code{gamma}), and intercepts (\code{beta0}, \code{gamma0}).
#'   \item \code{residuals}: A sparse matrix of the fitted residuals.
#'   \item \code{Xr}, \code{Zr}: The pxp and qxq R matrices generated from the QR-decomposition
#'         of the row and column covariates. They are copied from `data` and
#'         used to transform the estimated coefficients to
#'         the original scale. (used for the `summary` method)
#'   \item \code{meta}: A list of fitting metadata, including the iteration count,
#'         convergence status, and sum of squares components (used for the `print` method).
#'   \item \code{convergence}: The convergence control parameters used.
#'   \item \code{model}: The logical model structure inherited from `data`.
#'   \item \code{meta_data}: Variable metadata inherited from `data`.
#' }
#'
#' @seealso [imr_data()], [imr_convergence()], [print.imr_fit()], [summary.imr_fit()], [coef.imr_fit()]
#' @examples
#' # create sample data
#' Y <- matrix(
#'   c(2, NA, 3,
#'   4, .5, NA,
#'   NA, NA, 5), 3, byrow= TRUE
#' )
#'
#' # create covariate matrix of 2 variables
#' X <- matrix(rnorm(3*2), 3, 2)
#'
#' # create the data object
#' data <- imr_data(Y =  Y, X = X, val_prop = 0.0)
#'
#' # update the model to add row intercepts
#' data <- update(data, row_intercept = TRUE)
#'
#' # fit the model
#' fit <- imr_fit(data, rank = 2)
#'
#' # print the model fit summary
#' print(fit)
#'
#' # print a summary of the fitted coefficients
#' summary(fit)
#'
#' # extract the coefficients
#' coefs <- coef(fit)
#'
#' # estimate the target matrix
#' target <- reconstruct(fit, data)$estimates
#'
#' # compute estimates of the training data
#' estimates <- reconstruct_partial(fit, data, data$Y@i, data$Y@p, return_matrix = FALSE)
#'
#' # compute the training Root Mean Squared Error
#' evaluate(estimates, data$Y@x, metric = "RMSE")
#'
#' @references
#' Fouda, K., Labbe, A., & Oualkacha, K. (2026).
#' \emph{Incomplete Matrix Regression}.
#' \url{https://arxiv.org/abs/2606.26325}
#'
#' @export
imr_fit <- function(
    data,
    rank = 2,
    lambda_m = 0,
    lambda_beta = 0,
    lambda_gamma = 0,
    convergence = imr_convergence(),
    warm_start = NULL,
    training = FALSE # if training use y_train instead of Y.
) {
  # validation
  stopifnot(inherits(data, "imr_data"))
  stopifnot(inherits(convergence, "imr_convergence"))


  if (inherits(warm_start, "imr_fit")) {
    warm_start <- warm_start$coefficients
  }
  model <- data$model
  if(model$row_covariates)
    stopifnot(is.numeric(lambda_beta) && lambda_beta >= 0)
  if(model$col_covariates)
    stopifnot(is.numeric(lambda_gamma) && lambda_gamma >= 0)
  if(model$low_rank_component)
    stopifnot(is.numeric(rank) && rank > 0 && is.numeric(lambda_m) && lambda_m >= 0)

  result_list <- imr_solver(
    Y = if (training) data$y_train else data$Y,
    X = if (model$row_covariates) data$Xq else NULL,
    Z = if (model$col_covariates) data$Zq else NULL,
    r = if (model$low_rank_component) round(rank) else NULL,
    lambda_m = if (model$low_rank_component) lambda_m else NULL,
    lambda_beta = lambda_beta,
    lambda_gamma = lambda_gamma,
    Ur = if (model$low_rank_component && model$row_similarity) data$similarity_row$U else NULL,
    dr = if (model$low_rank_component && model$row_similarity) data$similarity_row$d else NULL,
    Uc = if (model$low_rank_component && model$col_similarity) data$similarity_col$U else NULL,
    dc = if (model$low_rank_component && model$col_covariates) data$similarity_col$d else NULL,
    row_intercept = model$row_intercept,
    col_intercept = model$col_intercept,
    shared_beta = model$shared_beta,
    shared_gamma = model$shared_gamma,
    convergence = convergence,
    warm_start = warm_start
  )

  # 5. Construct Final Object
  if (!training) {
    ss <- function(x) sum((x - mean(x))^2)
    sum_squares <- list(
      sst = ss(data$Y@x),                          # centered total SS
      sse = ss(result_list$residuals@x),           # centered residual SS
      rss = sum(result_list$residuals@x^2)         # uncentered residual SS (for RMSE / R^2)
    )
    if (data$model$row_covariates) {
      coefs <- if (data$model$shared_beta) {
        matrix(result_list$beta, data$meta$num_X_vars, data$meta$dimensions[2])
      } else {
        result_list$beta
      }
      sum_squares$ssrc <- ss(partial_crossprod(data$Xq, coefs, data$Y@i, data$Y@p))
    } else {
      sum_squares$ssrc <- 0
    }
    if (data$model$col_covariates) {
      coefs <- if (data$model$shared_gamma) {
        matrix(result_list$gamma, data$meta$dimensions[1], data$meta$num_Z_vars, TRUE)
      } else {
        result_list$gamma
      }
      sum_squares$sscc <- ss(partial_crossprod(coefs, data$Zq, data$Y@i, data$Y@p, TRUE))
    } else {
      sum_squares$sscc <- 0
    }
    if (data$model$row_intercept) {
      sum_squares$ssri <- ss(partial_crossprod(
        as.matrix(result_list$beta0),
        diag(1, 1, data$meta$dimensions[2]),
        data$Y@i, data$Y@p
      ))
    } else {
      sum_squares$ssri <- 0
    }
    if (data$model$col_intercept) {
      sum_squares$ssci <- ss(partial_crossprod(
        diag(1, data$meta$dimensions[1], 1),
        t(as.matrix(result_list$gamma0)),
        data$Y@i, data$Y@p
      ))
    } else {
      sum_squares$ssci <- 0
    }
    if (data$model$low_rank_component) {
      sum_squares$ssm <- ss(partial_crossprod(
        result_list$u,
        t(t(result_list$v) * result_list$d),
        data$Y@i, data$Y@p, TRUE
      ))
    } else {
      sum_squares$ssm <- 0
    }
  } else {
    sum_squares <- NULL
  }
  structure(
    list(
      coefficients = list(
        u = result_list$u,
        d = result_list$d,
        v = result_list$v,
        beta = result_list$beta,
        gamma = result_list$gamma,
        beta0 = result_list$beta0,
        gamma0 = result_list$gamma0
      ),
      residuals = result_list$residuals,
      Xr = if (model$row_covariates) data$Xr else NULL,
      Zr = if (model$col_covariates) data$Zr else NULL,
      meta = list(
        rank = rank,
        lambdas = c(M = lambda_m, beta = lambda_beta, gamma = lambda_gamma),
        intercepts = c(row = model$row_intercept, col = model$col_intercept),
        shared_effects = c(beta = model$shared_beta, gamma = model$shared_gamma),
        n_iter = result_list$n_iter,
        converged = result_list$n_iter < convergence$maxit,
        training = training,
        # statistic for print function
        sum_squares = sum_squares
      ),
      convergence = convergence,
      model = data$model,
      meta_data = data$meta
    ),
    class = "imr_fit"
  )
}


#' Fit Incomplete Matrix Regression (IMR) Model
#'
#' Not exported
#' @noRd
imr_solver <- function(
    Y, X, Z,
    row_intercept, col_intercept,
    shared_beta, shared_gamma,
    r, lambda_m, lambda_beta, lambda_gamma,
    Ur, dr, Uc, dc,
    convergence,
    warm_start
) {
  # Input checks & setup ----------------------------------------------------
  stopifnot(is_incomplete(Y))
  dims <- dim(Y)
  nr <- dims[1]
  nc <- dims[2]
  nz <- Matrix::nnzero(Y, na.counted = TRUE)
  irow <- Y@i
  pcol <- Y@p
  Y@x <- Y@x + 0 # force a copy so the original matrix doesn't get modified by C++

  # Unpack convergence ----------------------------------------------------------
  maxit <- convergence$maxit
  thresh <- convergence$thresh
  trace <- convergence$trace
  ls_initial <- convergence$ls_initial

  # Laplacian flags (L_* expected as eigendecompositions) -------------------
  beta_flag <- !(is.null(X))
  gamma_flag <- !(is.null(Z))
  nuclear_r_flag <- !(is.null(Ur) || is.null(dr))
  nuclear_c_flag <- !(is.null(Uc) || is.null(dc))
  low_rank_flag <- !(is.null(r) || is.null(lambda_m) || r <= 0)
  if (!low_rank_flag) ls_initial <- FALSE
  #-------------------------------------------------
  if (nuclear_r_flag) dr <- dr * lambda_m
  if (nuclear_c_flag) dc <- dc * lambda_m
  #--------------------------------------------------
  # initial everything to null ------------------------
  beta <- gamma <- beta0 <- gamma0 <- U <- V <- Dsq <- NULL

  # 3) Warm-start or initialize ------------------------------------------------
  if (!is.null(warm_start)) {
    warm_start <- verify_warm_start(warm_start, r)
  }

  if (!is.null(warm_start)) {
    required <- c("u", "d", "v", "beta", "gamma", "beta0", "gamma0")
    if (!all(required %in% names(warm_start))) {
      stop("warm_start missing components: u, d, v, beta, gamma, beta0, gamma0")
    }

    if (beta_flag) {
      beta <- warm_start$beta
      if (shared_beta) {
        xbeta <- X %*% beta
      } else {
        xb_obs <- partial_crossprod(X, beta, irow, pcol)
      }
    }
    if (gamma_flag) {
      gamma <- warm_start$gamma
      if (shared_gamma) {
        gammaz <- tcrossprod(gamma, Z)
      } else {
        zg_obs <- partial_crossprod(gamma, Z, irow, pcol, TRUE)
      }
    }
    if (row_intercept) {
      beta0 <- warm_start$beta0
    }

    if (col_intercept) {
      gamma0 <- warm_start$gamma0
    }

    U <- warm_start$u
    V <- warm_start$v
    Dsq <- warm_start$d
  } else {
    if (ls_initial) {
      mfit <- imr_solver(
        Y = Y, X = X, Z = Z,
        row_intercept = row_intercept, col_intercept = col_intercept,
        shared_beta = shared_beta, shared_gamma = shared_gamma,
        r = 0, lambda_m = NULL, lambda_beta = lambda_beta, lambda_gamma = lambda_gamma,
        Ur = NULL, dr = NULL, Uc = NULL, dc = NULL,
        convergence = convergence,
        warm_start = NULL
      )

      if (beta_flag) {
        beta <- mfit$beta
        if (shared_beta) {
          xbeta <- X %*% beta
        } else {
          xb_obs <- partial_crossprod(X, beta, irow, pcol)
        }
      }
      if (gamma_flag) {
        gamma <- mfit$gamma
        if (shared_gamma) {
          gammaz <- tcrossprod(gamma, Z)
        } else {
          zg_obs <- partial_crossprod(gamma, Z, irow, pcol, TRUE)
        }
      }
      if (row_intercept) {
        beta0 <- mfit$beta0
      }
      if (col_intercept) {
        gamma0 <- mfit$gamma0
      }

      init <- svd_opt(mfit$residuals, r)
    } else {
      if (beta_flag) {
        if (shared_beta) {
          beta <- rep(0, ncol(X))
          xbeta <- rep(0, nr)
        } else {
          beta <- matrix(0, ncol(X), nc)
          xb_obs <- rep(0, nz)
        }
      }
      if (gamma_flag) {
        if (shared_gamma) {
          gamma <- rep(0, ncol(Z))
          gammaz <- rep(0, nc)
        } else {
          gamma <- matrix(0, nr, ncol(Z))
          zg_obs <- rep(0, nz)
        }
      }
      if (row_intercept) {
        beta0 <- rep(0, nr)
      }
      if (col_intercept) {
        gamma0 <- rep(0, nc)
      }
      if (low_rank_flag) {
        init <- svd_opt(Y, r)
      }
    }

    if (low_rank_flag) {
      U <- init$u
      Dsq <- init$d
      V <- init$v
      rm(init)
    }
  }


  #  Update residuals (first iteration only)  -----------------------------
  if (low_rank_flag) {
    M_obs <- partial_crossprod(U, t(t(V) * Dsq), irow, pcol, TRUE)
    Y@x <- Y@x - M_obs
  }
  if (!is.null(warm_start) || (is.null(warm_start) && ls_initial)) {
    if (beta_flag && !shared_beta) Y@x <- Y@x - xb_obs
    if (gamma_flag && !shared_gamma) Y@x <- Y@x - zg_obs
    if (beta_flag && shared_beta) add_to_rows_inplace_cpp(Y@x, irow, -xbeta)
    if (gamma_flag && shared_gamma) add_to_cols_inplace_cpp(Y@x, pcol, -gammaz)
    if (row_intercept) add_to_rows_inplace_cpp(Y@x, irow, -beta0)
    if (col_intercept) add_to_cols_inplace_cpp(Y@x, pcol, -gamma0)
  }

  #  Main loop ---------------------------------------------------------------
  ratio <- Inf
  iter <- 0
  while (ratio > thresh && iter < maxit) {
    iter <- iter + 1

    U_old <- U
    V_old <- V
    D_old <- Dsq
    beta_old <- beta
    gamma_old <- gamma

    if (low_rank_flag) {
      #  Update (V, Dsq, U) from the "B" side --------------------------------
      # B_mat = BD
      if (nuclear_c_flag) {
        BD <- update_B_sim_cpp(Y, U, V, Dsq, Uc, dc)
      } else {
        BD <- update_B_cpp(Y, U, V, Dsq, lambda_m)
      }

      BD <- svd_small_nc_cpp(BD)
      V <- BD$u
      #Dsq <- tidyr::replace_na(BD$d, 0)
      Dsq <- BD$d
      Dsq[is.na(Dsq)] <- 0

      U <- U %*% BD$v

      # update Y
      old_val <- M_obs
      M_obs <- partial_crossprod(U, t(t(V) * Dsq), irow, pcol, TRUE)
      Y@x <- Y@x + old_val - M_obs


      # 4.6 Update (U, Dsq, V) from the "A" side --------------------------------
      # A_mat <- AD
      if (nuclear_r_flag) {
        AD <- update_A_sim_cpp(Y, U, V, Dsq, Ur, dr)
      } else {
        AD <- update_A_cpp(Y, U, V, Dsq, lambda_m)
      }

      AD <- svd_small_nc_cpp(AD)
      U <- AD$u
      #Dsq <- tidyr::replace_na(AD$d, 0)
      Dsq <- AD$d
      Dsq[is.na(Dsq)] <- 0

      V <- V %*% AD$v

      # update Y
      old_val <- M_obs
      M_obs <- partial_crossprod(U, t(t(V) * Dsq), irow, pcol, TRUE)
      Y@x <- Y@x + old_val - M_obs
    }

    #  Update beta via soft-threshold --------------------------------------
    if (beta_flag) {
      if (shared_beta) {
        beta <- soft_threshold_cpp(
          crossprod(X, row_means_cpp(Y@x, Y@i, nr)) + beta,
          lambda_beta
        )
        old_val <- xbeta
        xbeta <- X %*% beta
        change <- old_val - xbeta
        add_to_rows_inplace_cpp(Y@x, irow, change)
      } else {
        beta <- soft_threshold_cpp(
          as.matrix((crossprod(X, Y)) + beta),
          lambda_beta
        )
        old_val <- xb_obs
        xb_obs <- partial_crossprod(X, beta, irow, pcol)
        Y@x <- Y@x + old_val - xb_obs
      }
    }


    #  Update gamma via soft-threshold -------------------------------------
    if (gamma_flag) {
      if (shared_gamma) {
        gamma <- soft_threshold_cpp(
          col_means_cpp(Y@x, Y@p, nc) %*% Z + gamma,
          lambda_gamma
        )
        old_val <- gammaz
        gammaz <- tcrossprod(gamma, Z)
        change <- old_val - gammaz
        add_to_cols_inplace_cpp(Y@x, pcol, change)
      } else {
        gamma <- soft_threshold_cpp(
          as.matrix(Y %*% Z + gamma),
          lambda_gamma
        )
        old_val <- zg_obs
        zg_obs <- partial_crossprod(gamma, (Z), irow, pcol, TRUE)
        Y@x <- Y@x + old_val - zg_obs
      }
    }


    # Intercepts (row/column) ---------------------------------------------
    # Row-level intercepts (beta0), then apply delta to residuals.
    if (row_intercept) {
      old_val <- beta0
      beta0 <- row_means_cpp(Y@x, Y@i, nr) + beta0
      change <- old_val - beta0
      add_to_rows_inplace_cpp(Y@x, irow, change)
    }

    # Column-level intercepts (gamma0), then apply delta to residuals.
    if (col_intercept) {
      old_val <- gamma0
      gamma0 <- col_means_cpp(Y@x, Y@p, nc) + gamma0
      change <- old_val - gamma0
      add_to_cols_inplace_cpp(Y@x, pcol, change)
    }

    # 4.7 Convergence check ----------------------------------------------------
    ratio <- 0
    if (low_rank_flag) {
      ratio <- frob_ratio_cpp(U_old, D_old, V_old, U, Dsq, V)
    }
    if (beta_flag) {
      denom <- sum(beta_old * beta_old)
      if (denom > 0) {
        ratio <- ratio + sum((beta_old - beta)^2) / denom
      }
    }
    if (gamma_flag) {
      denom <- sum(gamma_old * gamma_old)
      if (denom > 0) {
        ratio <- ratio + sum((gamma_old - gamma)^2) / denom
      }
    }
    if (trace) {
      obj <- (0.5 * sum(Y@x^2) +
                ifelse(low_rank_flag, lambda_m * sum(Dsq), 0) +
                ifelse(beta_flag, lambda_beta * sum(abs(beta)), 0) +
                ifelse(gamma_flag, lambda_gamma * sum(abs(gamma)), 0)
      ) / nz
      cat(iter, " obj=", round(obj, 5), " ratio=", ratio, "\n")
    }
  }
  if (iter == maxit) {
    message("Did not converge in ", maxit, " iterations.")
  }

  # 5) Trim effective rank and return -----------------------------------------
  if (low_rank_flag) {
    r_eff <- min(max(1, sum(Dsq > 0)), r)
    U <- U[, seq_len(r_eff), drop = FALSE]
    Dsq <- Dsq[seq_len(r_eff)]
    V <- V[, seq_len(r_eff), drop = FALSE]
  }

  list(
    residuals = Y,
    u = U,
    d = Dsq,
    v = V,
    beta = beta,
    gamma = gamma,
    beta0 = beta0,
    gamma0 = gamma0,
    n_iter = iter
  )
}


#' @title Summary of the model's fit operation
#' @param x An `imr_fit` object
#' @param ... Additional arguments to comply with generic function
#' @seealso [imr_fit()], [summary.imr_fit()]
#' @inherit imr_fit examples
#' @export
#' @method print imr_fit
print.imr_fit <- function(x, ...) {
  cat("\n====================================================")
  cat("\n===    Incomplete Matrix Regression (IMR) Fit    ===")
  cat("\n====================================================\n")


  sym <- .imr_symbols()

  has_low_rank <- !is.null(x$coefficients$d) && length(x$coefficients$d) > 0
  has_row_cov <- !is.null(x$coefficients$beta)
  has_col_cov <- !is.null(x$coefficients$gamma)
  has_row_int <- !is.null(x$coefficients$beta0)
  has_col_int <- !is.null(x$coefficients$gamma0)

  # --- 1. Equation (intercepts first, then covariates, then latent term) ---
  terms <- c()
  if (has_row_int) terms <- c(terms, sym$beta0)
  if (has_col_int) terms <- c(terms, sym$Gamma0)
  if (has_row_cov) {
    term <- paste0("X", sym$dot, sym$beta)
    terms <- c(terms, if (x$meta$shared_effects["beta"]) paste0(term, " (shared)") else term)
  }
  if (has_col_cov) {
    term <- paste0(sym$Gamma, sym$dot, "Z")
    terms <- c(terms, if (x$meta$shared_effects["gamma"]) paste0(term, " (shared)") else term)
  }
  if (has_low_rank) terms <- c(terms, "M")
  if (length(terms) == 0) terms <- c("0")

  cat(sprintf("Formula :  Y ~ %s\n", paste(terms, collapse = " + ")))
  status <- if (x$meta$converged) "Converged" else "Did NOT converge"
  cat(sprintf("Status  : %s (in %d iterations)\n", status, x$meta$n_iter))
  cat(sprintf(
    "Target  : %d x %d matrix (%2.2f%% missing)\n", x$meta_data$dimensions[1],
    x$meta_data$dimensions[2], x$meta_data$sparsity * 100
  ))

  # --- 2. Coefficient Dimensions ---
  get_dim_str <- function(coef) {
    if (is.matrix(coef)) {
      return(sprintf("%d x %d matrix", nrow(coef), ncol(coef)))
    } else {
      return(sprintf("length %d vector", length(coef)))
    }
  }

  cat("\n-- Dimensions --\n")
  dim_line <- function(symbol, desc, val) {
    cat(sprintf("  %-2s (%-14s) : %s\n", symbol, desc, val))
  }
  if (has_row_cov) dim_line(sym$beta,   "row covariates", get_dim_str(x$coefficients$beta))
  if (has_col_cov) dim_line(sym$Gamma,  "col covariates", get_dim_str(x$coefficients$gamma))
  if (has_row_int) dim_line(sym$beta0,  "row intercepts", get_dim_str(x$coefficients$beta0))
  if (has_col_int) dim_line(sym$Gamma0, "col intercepts", get_dim_str(x$coefficients$gamma0))
  if (has_low_rank) {
    dim_line("M", "latent factors", sprintf(
      "U(%d x %d), D(length %d), V(%d x %d)",
      nrow(x$coefficients$u), ncol(x$coefficients$u),
      length(x$coefficients$d),
      nrow(x$coefficients$v), ncol(x$coefficients$v)
    ))
  }

  # --- 3. Fit Statistics ---
  if (!is.null(x$meta$sum_squares)) {
    sst <- x$meta$sum_squares$sst
    rss <- x$meta$sum_squares$rss
    if (is.null(rss)) rss <- sum(x$residuals@x^2)
    n <- length(x$residuals@x)
    rmse <- sqrt(rss / n)                 # true RMSE (matches evaluate())
    r2 <- 1 - (rss / sst)                 # standard pseudo R^2

    # Ensure R2 isn't negative
    r2_str <- if (r2 < 0) "< 0 (Poor Fit)" else sprintf("%.4f", r2)

    cat("\n-- Fit (in-sample, on observed entries) --\n")
    cat(sprintf("RMSE       : %s\n", .imr_fmt_num(rmse)))
    cat(sprintf("Pseudo R2  : %s\n", r2_str))
  }

  # --- 4. Hyperparameters ---
  cat("\n-- Penalties & Hyperparameters --\n")
  if (has_low_rank) {
    cat(sprintf("Rank (r)          : %d\n", x$meta$rank))
    cat(sprintf("Lambda M          : %s\n", .imr_fmt_num(x$meta$lambdas["M"])))
  }
  if (has_row_cov) {
    cat(sprintf("Lambda Beta       : %s\n", .imr_fmt_num(x$meta$lambdas["beta"])))
  }
  if (has_col_cov) {
    cat(sprintf("Lambda Gamma      : %s\n", .imr_fmt_num(x$meta$lambdas["gamma"])))
  }
  if (has_low_rank) {
    cat(sprintf("Row Similarity    : %s\n", ifelse(x$model$row_similarity, "Active", "None")))
    cat(sprintf("Column Similarity : %s", ifelse(x$model$col_similarity, "Active", "None")))
  }

  cat("\n====================================================\n")

  invisible(x)
}

#' @title Summary of the fitted model's parameters
#' @param object An `imr_fit` object
#' @param ... Additional arguments to comply with generic function
#' @seealso [imr_fit()], [print.imr_fit()]
#' @inherit imr_fit examples
#' @importFrom stats sd
#' @export
#' @method summary imr_fit
summary.imr_fit <- function(object, ...) {
  cat("\n=====================================================")
  cat("\n=== Summary of Incomplete Matrix Regression (IMR) ===")
  cat("\n=====================================================\n")

  sym <- .imr_symbols()

  #-- first part: training object metrics:

  sst <- object$meta$sum_squares$sst
  rss <- object$meta$sum_squares$rss
  if (is.null(rss)) rss <- sum(object$residuals@x^2)
  ssrc <- object$meta$sum_squares$ssrc
  sscc <- object$meta$sum_squares$sscc
  ssri <- object$meta$sum_squares$ssri
  ssci <- object$meta$sum_squares$ssci
  ssm <- object$meta$sum_squares$ssm
  sss <- ssrc + sscc + ssri + ssci + ssm

  n <- length(object$residuals@x)
  rmse <- sqrt(rss / n)                 # true RMSE (matches evaluate())
  r2 <- 1 - (rss / sst)                 # standard pseudo R^2
  explained <- sst - rss                # explained SS (== r2 * sst)

  cat("\nGoodness of Fit (in-sample, on observed entries)")
  cat("\n-------------------------------------------------------------\n")
  cat(sprintf("RMSE                    : %s\n", .imr_fmt_num(rmse)))
  cat(sprintf("MSE                     : %s\n", .imr_fmt_num(rss / n)))
  r2_str <- if (r2 < 0) "< 0 (Poor Fit)" else .imr_fmt_pct(100 * r2)
  cat(sprintf("Pseudo R2 (1 - RSS/SST) : %s\n", r2_str))

  cat("\nVariance Decomposition (share of explained variance)")
  cat("\n-------------------------------------------------------------\n")
  if (explained <= 0) {
    cat("Model explains no variance beyond the grand mean (Pseudo R2 <= 0);\n")
    cat("component decomposition omitted.\n")
  } else {
    # Each component's centered variance on observed cells, plus a non-additive
    # remainder, all expressed as a share of the explained variance. The shares
    # sum to 100% by construction.
    comp_line <- function(label, ss) {
      cat(sprintf("  %-24s : %s\n", label, .imr_fmt_pct(100 * ss / explained)))
    }
    if (object$model$low_rank_component) comp_line("Latent Matrix (M)", ssm)
    if (object$model$row_covariates)     comp_line(sprintf("Row Covariates (X%s%s)", sym$dot, sym$beta), ssrc)
    if (object$model$col_covariates)     comp_line(sprintf("Col Covariates (%s%sZ)", sym$Gamma, sym$dot), sscc)
    if (object$model$row_intercept)      comp_line(sprintf("Row Intercepts (%s)", sym$beta0), ssri)
    if (object$model$col_intercept)      comp_line(sprintf("Col Intercepts (%s)", sym$Gamma0), ssci)
    comp_line("Overlap / non-additive", explained - sss)
    cat("(Overlap is due to regularization.)\n")
  }
  cat("-------------------------------------------------------------\n")

  cat("\n Model Estimates")
  cat("\n-------------------------------------------------------------\n")

  summarize_covariates <- function(coefs, names, rows = FALSE, len = NA) {
    shared <- nrow(coefs) == 1

    cat(sprintf(
      "\n-- %s Covariates --\nMode: %s (%s)\n",
      ifelse(rows, "Row", "Column"),
      ifelse(shared, paste0("Shared across ", ifelse(rows, "columns", "rows")),
             paste0(ifelse(rows, "Column", "Row"), "-specific")
      ),
      ifelse(shared, sprintf("%s = %d", ifelse(rows, "p", "q"), ncol(coefs)),
             sprintf("%d x %d matrix", nrow(coefs), ncol(coefs))
      )
    ))
    if (shared) {
      vec <- data.frame(Estimate = t(coefs))
      rownames(vec) <- names
      vec <- round(vec, 4)
      print(format(vec, justify = "right"))
    } else {
      cat(sprintf(
        "Summary of effects across %d %s\n", len,
        ifelse(rows, "columns", "rows")
      ))
      summary <- data.frame(
        Mean = colMeans(coefs),
        SD = apply(coefs, 2, sd),
        Min = apply(coefs, 2, min),
        Max = apply(coefs, 2, max),
        Sparsity = sprintf("%.2f%%", colMeans(round(coefs, 6) == 0) * 100),
        `L2-Norm` = apply(coefs, 2, function(x) sqrt(sum(x^2))),
        row.names = names
      )
      summary <- summary[order(summary$L2.Norm, decreasing = TRUE), ]
      summary[, -5] <- round(summary[, -5], 4)
      print(format(summary, justify = "right"))
    }
  }

  if (object$model$row_covariates) {
    beta <- inv(object$Xr) %*% object$coefficients$beta
    summarize_covariates(
      t(beta), object$meta_data$names_X_vars,
      TRUE,
      object$meta_data$dimensions[2]
    )
  }
  if (object$model$col_covariates) {
    gamma <- tcrossprod(object$coefficients$gamma, inv(object$Zr))
    summarize_covariates(
      gamma, object$meta_data$names_Z_vars,
      FALSE,
      object$meta_data$dimensions[1]
    )
  }

  if (object$model$row_intercept || object$model$col_intercept) {
    cat("\n-- Intercepts --")
    if (object$model$row_intercept) {
      coefs <- object$coefficients$beta0
      cat(sprintf("\nRow Intercepts    (n=%d) | ", length(coefs)))
      cat(sprintf(
        "Mean: %.4f | SD: %.4f | Min: %.4f | Max: %.4f\n",
        mean(coefs), sd(coefs), min(coefs), max(coefs)
      ))
    }
    if (object$model$col_intercept) {
      coefs <- object$coefficients$gamma0
      cat(sprintf("Column Intercepts (m=%d) | ", length(coefs)))
      cat(sprintf(
        "Mean: %.4f | SD: %.4f | Min: %.4f | Max: %.4f\n",
        mean(coefs), sd(coefs), min(coefs), max(coefs)
      ))
    }
  }
  if (object$model$low_rank_component) {
    cat("\n-- Latent Component --")
    cat(sprintf("\nRank (r): %d\nSingular Values:\n", length(object$coefficients$d)))
    print(round(object$coefficients$d, 4))
  }

  invisible(object)
}


#' @title Summary of the model's convergence parameters
#' @param x An `imr_convergence` object
#' @param ... Additional arguments to comply with generic function
#' @seealso [imr_convergence()] [imr_fit()]
#' @inherit imr_convergence examples
#' @export
#' @method print imr_convergence
print.imr_convergence <- function(x, ...) {
  cat("\n== IMR Convergence Parameters ==\n")

  cat(sprintf("Max Iterations: %d\n", x$maxit))
  cat(sprintf("Threshold:      %g\n", x$thresh))

  init_method <- if (x$ls_initial) "Least Squares" else "Randomized"
  cat(sprintf("Initialization: %s\n", init_method))

  # 3. Trace/Verbosity
  trace_status <- if (x$trace) "Enabled" else "Disabled"
  cat(sprintf("Trace Progress: %s\n", trace_status))

  cat("================================\n")
  invisible()
}

#' @title Extract the fitted model's coefficients
#' @param object An `imr_fit` object
#' @param ... Additional arguments to comply with generic function
#' @seealso [imr_fit()]
#' @inherit imr_fit examples
#' @export
#' @importFrom stats coef coefficients
#' @method coef imr_fit
coef.imr_fit <- function(object, ...) {
  return(object$coefficients)
}


#' @title Matrix Completion using Row and Column Means
#'
#' @description
#' A naive matrix completion method that imputes missing entries by filling them
#' with the average of their corresponding row and column means.
#'
#' @param mat A matrix object. This can be an `Incomplete` matrix, a standard
#'   sparse matrix, or a base R dense matrix. If it is not already of class
#'   `Incomplete`, it will be converted internally prior to imputation.
#'
#' @details
#' The function efficiently computes row and column means using an internal C++
#' functions, excluding missing entries. It replaces
#' each missing value at index \eqn{(i, j)} with the mean of the  i-th
#' row mean and the j-th column mean.
#'
#' @return A dense matrix of class `Incomplete`.
#'
#' @export
#'
#' @examples
#'
#' # Create a sample matrix with missing values (NAs)
#' mat <- matrix(c(1, NA, 3, 4, 5, NA, 7, 8, 9), nrow = 3)
#'
#' # Impute the missing values using row and column averages
#' mc_with_means(mat)
mc_with_means <- function(mat) {
  # Calculate row and column means, excluding NAs
  if (!is_incomplete(mat)) mat <- as_incomplete(mat)
  row_means <- row_means_cpp(mat@x, mat@i, nrow(mat))
  col_means <- col_means_cpp(mat@x, mat@p, ncol(mat))
  ij <- Matrix::which(mat == 0, arr.ind = TRUE)
  mat[ij] <- (row_means[ij[, 1]] + col_means[ij[, 2]]) / 2
  mat <- Matrix::drop0(mat)
  return(mat)
}
