#' Control Parameters for IMR Convergence
#'
#' @description
#' Defines and creates a structure for the convergence parameters used by the
#' IMR fit function.
#'
#' @param maxit Integer. The maximum number of iterations allowed for the fit
#'   function. Defaults to `600`.
#' @param thresh Numeric. The convergence threshold. Training stops early if
#'   the Frobenius difference between the new and old parameters falls below
#'   this value. Defaults to `1e-5`.
#' @param trace Logical. If `TRUE`, prints the Frobenius ratio and the loss
#'   function value at each iteration. Defaults to `FALSE`.
#' @param ls_initial Logical. If `TRUE` (the default), least-squares initial
#'   values are used. If `FALSE`, random initialization is used. It is highly
#'   recommended to leave this as `TRUE` to speed up convergence. Refer to
#'   the IMR article for more details on initialization.
#'
#' @return An object of class `"imr_convergence"`, which is a list containing
#'   the specified control parameters.
#'
#' @export
#'
#' @examples
#' # Use the default convergence parameters
#' imr_convergence()
imr_convergence <- function(maxit = 600,
                            thresh = 1e-5,
                            trace = FALSE,
                            ls_initial = TRUE) {
  structure(
    list(
      maxit = maxit,
      thresh = thresh,
      trace = trace,
      ls_initial = ls_initial
    ),
    class = "imr_convergence"
  )
}

#' Fit an IMR Model
#'
#' @description
#' The main function for fitting an Incomplete Matrix Regression (IMR) model.
#' It takes a prepared `imr_data` object and estimates the parameters based on the
#' specified model structure and regularization parameters.
#'
#' @param data An object of class `"imr_data"`. This object contains the response
#'   matrix, optional covariates and similarities, and the specific model structure to be fitted.
#' @param rank Integer. The rank of the low-rank component (\eqn{M=U D V^T}). This is
#'   required if the model structure includes a low-rank component. Defaults to `2`.
#' @param lambda_m Numeric. The regularization parameter for the low-rank component.
#'   Required if the low-rank component is included in the model. Defaults to `0`.
#' @param lambda_beta Numeric. The regularization parameter for the row covariates.
#'   Only used if row covariates are specified in the `imr_data` model structure.
#'   Defaults to `0`.
#' @param lambda_gamma Numeric. The regularization parameter for the column covariates.
#'   Only used if column covariates are specified in the `imr_data` model structure.
#'   Defaults to `0`.
#' @param convergence An object of class `"imr_convergence"`, generated by
#'   `imr_convergence()`. It dictates the maximum iterations, threshold, tracing,
#'   and initialization method.
#' @param warm_start An optional object of class `"imr_fit"`. If provided, the
#'   coefficients from this previous fit are used as the starting values for the
#'   new optimization, overriding the initialization strategy in `convergence`.
#'   Defaults to `NULL`.
#' @param training Logical. If `TRUE`, the model fits on `data$y_train` rather than
#'   the full `data$Y` matrix. This is primarily intended for internal use during
#'   cross-validation. Generally, users should leave this as `FALSE`. Defaults to `FALSE`.
#'
#' @return An object of class `"imr_fit"`. This is a list containing:
#' \itemize{
#'   \item \code{coefficients}: A list of the estimated model parameters, which may include
#'         the low-rank matrices (\code{u}, \code{d}, \code{v}), covariate effects
#'         (\code{beta}, \code{gamma}), and intercepts (\code{beta0}, \code{gamma0}).
#'   \item \code{residuals}: A sparse matrix of the fitted residuals.
#'   \item \code{Xr}, \code{Zr}: The pxp and qxq R matrices generated from the QR-decomposition
#'         of the row and column covariates. They are copied from `data` and
#'         used to transform the estimated coefficients to
#'         the original scale. (used for the `summary` method)
#'   \item \code{meta}: A list of fitting metadata, including the iteration count,
#'         convergence status, and sum of squares components (used for the `print` method).
#'   \item \code{convergence}: The convergence control parameters used.
#'   \item \code{model}: The logical model structure inherited from `data`.
#'   \item \code{meta_data}: Variable metadata inherited from `data`.
#' }
#'
#' @export
imr_fit <- function(
  data,
  rank = 2,
  lambda_m = 0,
  lambda_beta = 0,
  lambda_gamma = 0,
  convergence = imr_convergence(),
  warm_start = NULL,
  training = FALSE # if training use y_train instead of Y.
) {
  # validation
  stopifnot(inherits(data, "imr_data"))
  stopifnot(inherits(convergence, "imr_convergence"))


  if (inherits(warm_start, "imr_fit")) {
    warm_start <- warm_start$coefficients
  }
  model <- data$model
  stopifnot(model$row_covariates && is.numeric(lambda_beta) && lambda_beta >= 0)
  stopifnot(model$col_covariates && is.numeric(lambda_gamma) && lambda_gamma >= 0)
  stopifnot(model$low_rank_component && is.numeric(lambda_m) && lambda_m >= 0)
  stopifnot(model$low_rank_component && is.numeric(rank) && rank > 0)

  result_list <- imr_solver(
    Y = if (training) data$y_train else data$Y,
    X = if (model$row_covariates) data$Xq else NULL,
    Z = if (model$col_covariates) data$Zq else NULL,
    r = if (model$low_rank_component) round(rank) else NULL,
    lambda_m = if (model$low_rank_component) lambda_m else NULL,
    lambda_beta = lambda_beta,
    lambda_gamma = lambda_gamma,
    Ur = if (model$low_rank_component && model$row_similarity) data$similarity_row$U else NULL,
    dr = if (model$low_rank_component && model$row_similarity) data$similarity_row$d else NULL,
    Uc = if (model$low_rank_component && model$col_similarity) data$similarity_col$U else NULL,
    dc = if (model$low_rank_component && model$col_covariates) data$similarity_col$d else NULL,
    row_intercept = model$row_intercept,
    col_intercept = model$col_intercept,
    shared_beta = model$shared_beta,
    shared_gamma = model$shared_gamma,
    convergence = convergence,
    warm_start = warm_start
  )

  # 5. Construct Final Object
  if (!training) {
    ss <- function(x) sum((x - mean(x))^2)
    sum_squares <- list(
      sst = ss(data$Y@x),
      sse = ss(result_list$residuals@x)
    )
    if (data$model$row_covariates) {
      coefs <- if (data$model$shared_beta) {
        matrix(result_list$beta, data$meta$num_X_vars, data$meta$dimensions[2])
      } else {
        result_list$beta
      }
      sum_squares$ssrc <- ss(partial_crossprod(data$Xq, coefs, data$Y@i, data$Y@p))
    } else {
      sum_squares$ssrc <- 0
    }
    if (data$model$col_covariates) {
      coefs <- if (data$model$shared_gamma) {
        matrix(result_list$gamma, data$meta$dimensions[1], data$meta$num_Z_vars, TRUE)
      } else {
        result_list$gamma
      }
      sum_squares$sscc <- ss(partial_crossprod(coefs, data$Zq, data$Y@i, data$Y@p, TRUE))
    } else {
      sum_squares$sscc <- 0
    }
    if (data$model$row_intercept) {
      sum_squares$ssri <- ss(partial_crossprod(
        as.matrix(result_list$beta0),
        diag(1, 1, data$meta$dimensions[2]),
        data$Y@i, data$Y@p
      ))
    } else {
      sum_squares$ssri <- 0
    }
    if (data$model$col_intercept) {
      sum_squares$ssci <- ss(partial_crossprod(
        diag(1, data$meta$dimensions[1], 1),
        t(as.matrix(result_list$gamma0)),
        data$Y@i, data$Y@p
      ))
    } else {
      sum_squares$ssci <- 0
    }
    if (data$model$low_rank_component) {
      sum_squares$ssm <- ss(IMR:::partial_crossprod(
        result_list$u,
        t(t(result_list$v) * result_list$d),
        data$Y@i, data$Y@p, TRUE
      ))
    } else {
      sum_squares$ssm <- 0
    }
  } else {
    sum_squares <- NULL
  }
  structure(
    list(
      coefficients = list(
        u = result_list$u,
        d = result_list$d,
        v = result_list$v,
        beta = result_list$beta,
        gamma = result_list$gamma,
        beta0 = result_list$beta0,
        gamma0 = result_list$gamma0
      ),
      residuals = result_list$residuals,
      Xr = if (model$row_covariates) data$Xr else NULL,
      Zr = if (model$col_covariates) data$Zr else NULL,
      meta = list(
        rank = rank,
        lambdas = c(M = lambda_m, beta = lambda_beta, gamma = lambda_gamma),
        intercepts = c(row = model$row_intercept, col = model$col_intercept),
        shared_effects = c(beta = model$shared_beta, gamma = model$shared_gamma),
        n_iter = result_list$n_iter,
        converged = result_list$n_iter < convergence$maxit,
        training = training,
        # statistic for print function
        sum_squares = sum_squares
      ),
      convergence = convergence,
      model = data$model,
      meta_data = data$meta
    ),
    class = "imr_fit"
  )
}


#' Fit Incomplete Matrix Regression (IMR) Model
#'
#' Not exported
imr_solver <- function(
  Y, X, Z,
  row_intercept, col_intercept,
  shared_beta, shared_gamma,
  r, lambda_m, lambda_beta, lambda_gamma,
  Ur, dr, Uc, dc,
  convergence,
  warm_start
) {
  # Input checks & setup ----------------------------------------------------
  stopifnot(is.Incomplete(Y))
  dims <- dim(Y)
  nr <- dims[1]
  nc <- dims[2]
  nz <- Matrix::nnzero(Y, na.counted = TRUE)
  irow <- Y@i
  pcol <- Y@p
  Y@x <- Y@x + 0 # force a copy so the original matrix doesn't get modified by C++

  # Unpack convergence ----------------------------------------------------------
  maxit <- convergence$maxit
  thresh <- convergence$thresh
  trace <- convergence$trace
  ls_initial <- convergence$ls_initial

  # Laplacian flags (L_* expected as eigendecompositions) -------------------
  beta_flag <- !(is.null(X))
  gamma_flag <- !(is.null(Z))
  nuclear_r_flag <- !(is.null(Ur) || is.null(dr))
  nuclear_c_flag <- !(is.null(Uc) || is.null(dc))
  low_rank_flag <- !(is.null(r) || is.null(lambda_m) || r <= 0)
  if (!low_rank_flag) ls_initial <- FALSE
  #-------------------------------------------------
  if (nuclear_r_flag) dr <- dr * lambda_m
  if (nuclear_c_flag) dc <- dc * lambda_m
  #--------------------------------------------------
  # initial everything to null ------------------------
  beta <- gamma <- beta0 <- gamma0 <- U <- V <- Dsq <- NULL

  # 3) Warm-start or initialize ------------------------------------------------
  if (!is.null(warm_start)) {
    warm_start <- verify_warm_start(warm_start, r)
  }

  if (!is.null(warm_start)) {
    required <- c("u", "d", "v", "beta", "gamma", "beta0", "gamma0")
    if (!all(required %in% names(warm_start))) {
      stop("warm_start missing components: u, d, v, beta, gamma, beta0, gamma0")
    }

    if (beta_flag) {
      beta <- warm_start$beta
      if (shared_beta) {
        xbeta <- X %*% beta
      } else {
        xb_obs <- partial_crossprod(X, beta, irow, pcol)
      }
    }
    if (gamma_flag) {
      gamma <- warm_start$gamma
      if (shared_gamma) {
        gammaz <- tcrossprod(gamma, Z)
      } else {
        zg_obs <- partial_crossprod(gamma, Z, irow, pcol, TRUE)
      }
    }
    if (row_intercept) {
      beta0 <- warm_start$beta0
    }

    if (col_intercept) {
      gamma0 <- warm_start$gamma0
    }

    U <- warm_start$u
    V <- warm_start$v
    Dsq <- warm_start$d
  } else {
    if (ls_initial) {
      mfit <- imr_solver(
        Y = Y, X = X, Z = Z,
        row_intercept = row_intercept, col_intercept = col_intercept,
        shared_beta = shared_beta, shared_gamma = shared_gamma,
        r = 0, lambda_m = NULL, lambda_beta = lambda_beta, lambda_gamma = lambda_gamma,
        Ur = NULL, dr = NULL, Uc = NULL, dc = NULL,
        convergence = convergence,
        warm_start = NULL
      )

      if (beta_flag) {
        beta <- mfit$beta
        if (shared_beta) {
          xbeta <- X %*% beta
        } else {
          xb_obs <- partial_crossprod(X, beta, irow, pcol)
        }
      }
      if (gamma_flag) {
        gamma <- mfit$gamma
        if (shared_gamma) {
          gammaz <- tcrossprod(gamma, Z)
        } else {
          zg_obs <- partial_crossprod(gamma, Z, irow, pcol, TRUE)
        }
      }
      if (row_intercept) {
        beta0 <- mfit$beta0
      }
      if (col_intercept) {
        gamma0 <- mfit$gamma0
      }

      init <- IMR::svd_opt(mfit$residuals, r)
    } else {
      if (beta_flag) {
        if (shared_beta) {
          beta <- rep(0, ncol(X))
          xbeta <- rep(0, nr)
        } else {
          beta <- matrix(0, ncol(X), nc)
          xb_obs <- rep(0, nz)
        }
      }
      if (gamma_flag) {
        if (shared_gamma) {
          gamma <- rep(0, ncol(Z))
          gammaz <- rep(0, nc)
        } else {
          gamma <- matrix(0, nr, ncol(Z))
          zg_obs <- rep(0, nz)
        }
      }
      if (row_intercept) {
        beta0 <- rep(0, nr)
      }
      if (col_intercept) {
        gamma0 <- rep(0, nc)
      }
      if (low_rank_flag) {
        init <- IMR::svd_opt(Y, r)
      }
    }

    if (low_rank_flag) {
      U <- init$u
      Dsq <- init$d
      V <- init$v
      rm(init)
    }
  }


  #  Update residuals (first iteration only)  -----------------------------
  if (low_rank_flag) {
    M_obs <- partial_crossprod(U, t(t(V) * Dsq), irow, pcol, TRUE)
    Y@x <- Y@x - M_obs
  }
  if (!is.null(warm_start) || (is.null(warm_start) && ls_initial)) {
    if (beta_flag && !shared_beta) Y@x <- Y@x - xb_obs
    if (gamma_flag && !shared_gamma) Y@x <- Y@x - zg_obs
    if (beta_flag && shared_beta) add_to_rows_inplace_cpp(Y@x, irow, -xbeta)
    if (gamma_flag && shared_gamma) add_to_cols_inplace_cpp(Y@x, pcol, -gammaz)
    if (row_intercept) add_to_rows_inplace_cpp(Y@x, irow, -beta0)
    if (col_intercept) add_to_cols_inplace_cpp(Y@x, pcol, -gamma0)
  }

  #  Main loop ---------------------------------------------------------------
  ratio <- Inf
  iter <- 0
  while (ratio > thresh && iter < maxit) {
    iter <- iter + 1

    U_old <- U
    V_old <- V
    D_old <- Dsq
    beta_old <- beta
    gamma_old <- gamma

    if (low_rank_flag) {
      #  Update (V, Dsq, U) from the "B" side --------------------------------
      # B_mat = BD
      if (nuclear_c_flag) {
        BD <- IMR:::update_B_sim_cpp(Y, U, V, Dsq, Uc, dc)
      } else {
        BD <- IMR:::update_B_cpp(Y, U, V, Dsq, lambda_m)
      }

      BD <- IMR:::svd_small_nc_cpp(BD)
      V <- BD$u
      Dsq <- tidyr::replace_na(BD$d, 0)
      U <- U %*% BD$v

      # update Y
      old_val <- M_obs
      M_obs <- partial_crossprod(U, t(t(V) * Dsq), irow, pcol, TRUE)
      Y@x <- Y@x + old_val - M_obs


      # 4.6 Update (U, Dsq, V) from the "A" side --------------------------------
      # A_mat <- AD
      if (nuclear_r_flag) {
        AD <- IMR:::update_A_sim_cpp(Y, U, V, Dsq, Ur, dr)
      } else {
        AD <- IMR:::update_A_cpp(Y, U, V, Dsq, lambda_m)
      }

      AD <- IMR:::svd_small_nc_cpp(AD)
      U <- AD$u
      Dsq <- tidyr::replace_na(AD$d, 0)
      V <- V %*% AD$v

      # update Y
      old_val <- M_obs
      M_obs <- partial_crossprod(U, t(t(V) * Dsq), irow, pcol, TRUE)
      Y@x <- Y@x + old_val - M_obs
    }

    #  Update beta via soft-threshold --------------------------------------
    if (beta_flag) {
      if (shared_beta) {
        beta <- soft_threshold_cpp(
          crossprod(X, row_means_cpp(Y@x, Y@i, nr, nc)) + beta,
          lambda_beta
        )
        old_val <- xbeta
        xbeta <- X %*% beta
        change <- old_val - xbeta
        add_to_rows_inplace_cpp(Y@x, irow, change)
      } else {
        beta <- soft_threshold_cpp(
          as.matrix((crossprod(X, Y)) + beta),
          lambda_beta
        )
        old_val <- xb_obs
        xb_obs <- partial_crossprod(X, beta, irow, pcol)
        Y@x <- Y@x + old_val - xb_obs
      }
    }


    #  Update gamma via soft-threshold -------------------------------------
    if (gamma_flag) {
      if (shared_gamma) {
        gamma <- soft_threshold_cpp(
          col_means_cpp(Y@x, Y@p, nr, nc) %*% Z + gamma,
          lambda_gamma
        )
        old_val <- gammaz
        gammaz <- tcrossprod(gamma, Z)
        change <- old_val - gammaz
        add_to_cols_inplace_cpp(Y@x, pcol, change)
      } else {
        gamma <- soft_threshold_cpp(
          as.matrix(Y %*% Z + gamma),
          lambda_gamma
        )
        old_val <- zg_obs
        zg_obs <- partial_crossprod(gamma, (Z), irow, pcol, TRUE)
        Y@x <- Y@x + old_val - zg_obs
      }
    }


    # Intercepts (row/column) ---------------------------------------------
    # Row-level intercepts (beta0), then apply delta to residuals.
    if (row_intercept) {
      old_val <- beta0
      beta0 <- row_means_cpp(Y@x, Y@i, nr, nc) + beta0
      change <- old_val - beta0
      add_to_rows_inplace_cpp(Y@x, irow, change)
    }

    # Column-level intercepts (gamma0), then apply delta to residuals.
    if (col_intercept) {
      old_val <- gamma0
      gamma0 <- col_means_cpp(Y@x, Y@p, nr, nc) + gamma0
      change <- old_val - gamma0
      add_to_cols_inplace_cpp(Y@x, pcol, change)
    }

    # 4.7 Convergence check ----------------------------------------------------
    ratio <- 0
    if (low_rank_flag) {
      ratio <- frob_ratio_cpp(U_old, D_old, V_old, U, Dsq, V)
    }
    if (beta_flag) {
      denom <- sum(beta_old * beta_old)
      if (denom > 0) {
        ratio <- ratio + sum((beta_old - beta)^2) / denom
      }
    }
    if (gamma_flag) {
      denom <- sum(gamma_old * gamma_old)
      if (denom > 0) {
        ratio <- ratio + sum((gamma_old - gamma)^2) / denom
      }
    }
    if (trace) {
      obj <- (0.5 * sum(Y@x^2) +
        ifelse(low_rank_flag, lambda_m * sum(Dsq), 0) +
        ifelse(beta_flag, lambda_beta * sum(abs(beta)), 0) +
        ifelse(gamma_flag, lambda_gamma * sum(abs(gamma)), 0)
      ) / nz
      cat(iter, " obj=", round(obj, 5), " ratio=", ratio, "\n")
    }
  }
  if (iter == maxit) {
    warning("Did not converge in ", maxit, " iterations.")
  }

  # 5) Trim effective rank and return -----------------------------------------
  if (low_rank_flag) {
    r_eff <- min(max(1, sum(Dsq > 0)), r)
    U <- U[, seq_len(r_eff), drop = FALSE]
    Dsq <- Dsq[seq_len(r_eff)]
    V <- V[, seq_len(r_eff), drop = FALSE]
  }

  list(
    residuals = Y,
    u = U,
    d = Dsq,
    v = V,
    beta = beta,
    gamma = gamma,
    beta0 = beta0,
    gamma0 = gamma0,
    n_iter = iter
  )
}


#' @export
#' @method print imr_fit
print.imr_fit <- function(x, ...) {
  cat("\n====================================================")
  cat("\n===    Incomplete Matrix Regression (IMR) Fit    ===")
  cat("\n====================================================\n")


  has_low_rank <- !is.null(x$coefficients$d) && length(x$coefficients$d) > 0
  has_row_cov <- !is.null(x$coefficients$beta)
  has_col_cov <- !is.null(x$coefficients$gamma)
  has_row_int <- !is.null(x$coefficients$beta0)
  has_col_int <- !is.null(x$coefficients$gamma0)

  # --- 1. Equation ---
  terms <- c()
  if (has_row_cov) {
    beta_type <- if (x$meta$shared_effects["beta"]) "" else ""
    terms <- c(terms, paste0("X\u00b7\u03b2"))
  }
  if (has_col_cov) {
    gamma_type <- if (x$meta$shared_effects["gamma"]) "shared" else ""
    terms <- c(terms, paste0("\u03b3", "\u00b7Z"))
  }
  if (has_low_rank) terms <- c(terms, "M")
  if (has_row_int) terms <- c(terms, "\u03b2\u2080")
  if (has_col_int) terms <- c(terms, "\u03b3\u2080")
  if (length(terms) == 0) terms <- c("0")

  cat(sprintf("Formula :  Y ~ %s\n", paste(terms, collapse = " + ")))
  status <- if (x$meta$converged) "Converged" else "Did NOT converge"
  cat(sprintf("Status  : %s (in %d iterations)\n", status, x$meta$n_iter))
  cat(sprintf(
    "Target  : %d x %d matrix (%2.2f%% missing)\n", x$meta_data$dimensions[1],
    x$meta_data$dimensions[2], x$meta_data$sparsity * 100
  ))

  # --- 2. Coefficient Dimensions ---
  get_dim_str <- function(coef) {
    if (is.matrix(coef)) {
      return(sprintf("%d x %d matrix", nrow(coef), ncol(coef)))
    } else {
      return(sprintf("length %d vector", length(coef)))
    }
  }

  cat("\n-- Dimensions --\n")
  if (has_row_cov) cat(sprintf("  %-7s : %s\n", "\u03b2", get_dim_str(x$coefficients$beta)))
  if (has_col_cov) cat(sprintf("  %-7s : %s\n", "\u03b3", get_dim_str(x$coefficients$gamma)))
  if (has_row_int) cat(sprintf("  %-9s : %s\n", "\u03b2\u2080", get_dim_str(x$coefficients$beta0)))
  if (has_col_int) cat(sprintf("  %-9s : %s\n", "\u03b3\u2080", get_dim_str(x$coefficients$gamma0)))
  if (has_low_rank) {
    # It's also helpful to remind them of the dimensions of the latent factor matrices
    cat(sprintf(
      "  %-6s : U(%d x %d), D(length %d), V(%d x %d)\n",
      "M", nrow(x$coefficients$u), ncol(x$coefficients$u),
      length(x$coefficients$d),
      nrow(x$coefficients$v), ncol(x$coefficients$v)
    ))
  }

  # --- 3. Fit Statistics ---
  if (!is.null(x$meta$sum_squares)) {
    sse <- x$meta$sum_squares$sse
    sst <- x$meta$sum_squares$sst
    n <- length(x$residuals@x)
    mse <- sse / n
    rmse <- sqrt(mse)
    r2 <- 1 - (sse / sst)

    prepare_d <- function(x) ifelse(round(x, 4) >= 1e-4 || x == 0, sprintf("%.4f", x), "< 1e-4")

    # Ensure R2 isn't negative
    r2_str <- if (r2 < 0) "< 0 (Poor Fit)" else sprintf("%.4f", r2)

    cat("\n-- Fit Statistics --\n")
    cat(sprintf("RMSE       : %s\n", prepare_d(rmse)))
    cat(sprintf("MSE        : %s\n", prepare_d(mse)))
    cat(sprintf("Pseudo R2  : %s\n", r2_str))
  }

  # --- 4. Hyperparameters ---
  cat("\n-- Penalties & Hyperparameters --\n")
  if (has_low_rank) {
    cat(sprintf("Rank (r)          : %d\n", x$meta$rank))
    cat(sprintf("Lambda M          : %s\n", prepare_d(x$meta$lambdas["M"])))
  }
  if (has_row_cov) {
    cat(sprintf("Lambda Beta       : %s\n", prepare_d(x$meta$lambdas["beta"])))
  }
  if (has_col_cov) {
    cat(sprintf("Lambda Gamma      : %s\n", prepare_d(x$meta$lambdas["gamma"])))
  }
  if (has_low_rank) {
    cat(sprintf("Row Similarity    : %s\n", ifelse(x$model$row_similarity, "Active", "None")))
    cat(sprintf("Column Similarity : %s", ifelse(x$model$col_similarity, "Active", "None")))
  }

  cat("\n====================================================\n")

  invisible(x)
}

#' @export
#' @method summary imr_fit
summary.imr_fit <- function(object, ...) {
  cat("\n=====================================================")
  cat("\n=== Summary of Incomplete Matrix Regression (IMR) ===")
  cat("\n=====================================================\n")

  #-- first part: training object metrics:

  sst <- object$meta$sum_squares$sst
  sse <- object$meta$sum_squares$sse
  ssrc <- object$meta$sum_squares$ssrc
  sscc <- object$meta$sum_squares$sscc
  ssri <- object$meta$sum_squares$ssri
  ssci <- object$meta$sum_squares$ssci
  ssm <- object$meta$sum_squares$ssm
  sss <- ssrc + sscc + ssri + ssci + ssm


  exp_var <- 1 - (sse / sst)
  n <- length(object$residuals@x)
  mse <- sse / n
  rmse <- sqrt(mse)
  prepare_fmt <- function(x) ifelse(round(x, 1) >= 0.1 || x == 0, sprintf("%2.1f%%", x), "< 0.1%")
  prepare_d <- function(x) ifelse(round(x, 4) >= 1e-4 || x == 0, sprintf("%.4f", x), "< 1e-4")
  cat("\nGoodness of Fit (on observed entries)")
  cat("\n-------------------------------------------------------------\n")
  cat(sprintf("RMSE                                   : %s\n", prepare_d(rmse)))
  cat(sprintf("MSE                                    : %s\n", prepare_d(mse)))
  cat(sprintf("Total Explained Variance (1 - SSE/SST) : %s\n", prepare_fmt(100 * exp_var)))
  cat(sprintf("Unexplained Variance (SSE/SST)         : %s\n", prepare_fmt(100 * (sse / sst))))


  cat("\nRelative Contribution to Explained Variance")
  cat("\n-------------------------------------------------------------\n")
  cat(sprintf("Additive Components        : %2.1f%% of explained variance\n", 100 * sss / (sst - sse)))
  if (object$model$low_rank_component) {
    cat(sprintf("    |-- Latent Matrix      :    %s\n", prepare_fmt(100 * ssm / sss)))
  }
  if (object$model$row_covariates) {
    cat(sprintf("    |-- Row Covariates     :    %s\n", prepare_fmt(100 * ssrc / sss)))
  }
  if (object$model$col_covariates) {
    cat(sprintf("    |-- Column Covariates  :    %s\n", prepare_fmt(100 * sscc / sss)))
  }
  if (object$model$row_intercept) {
    cat(sprintf("    |-- Row Intercepts     :    %s\n", prepare_fmt(100 * ssri / sss)))
  }
  if (object$model$col_intercept) {
    cat(sprintf("    |-- Column Intercepts  :    %s\n", prepare_fmt(100 * ssci / sss)))
  }

  cat(sprintf("\nRegularization & Overlap   : %s of explained variance\n", prepare_fmt(100 * (1 - (sss / (sst - sse))))))
  cat("(Measures the deviation from orthogonal additivity due to shrinkage penalties and missing data.)\n")
  cat("-------------------------------------------------------------\n")

  cat("\n Model Estimates")
  cat("\n-------------------------------------------------------------\n")

  summarize_covariates <- function(coefs, names, rows = FALSE, len = NA) {
    shared <- nrow(coefs) == 1

    cat(sprintf(
      "\n-- %s Covariates --\nMode: %s (%s)\n",
      ifelse(rows, "Row", "Column"),
      ifelse(shared, paste0("Shared across ", ifelse(rows, "columns", "rows")),
        paste0(ifelse(rows, "Column", "Row"), "-specific")
      ),
      ifelse(shared, sprintf("%s = %d", ifelse(rows, "p", "q"), ncol(coefs)),
        sprintf("%d x %d matrix", nrow(coefs), ncol(coefs))
      )
    ))
    if (shared) {
      vec <- data.frame(Estimate = t(coefs))
      rownames(vec) <- names
      vec <- round(vec, 4)
      print(format(vec, justify = "right"))
    } else {
      cat(sprintf(
        "Summary of effects across %d %s\n", len,
        ifelse(rows, "columns", "rows")
      ))
      summary <- data.frame(
        Mean = colMeans(coefs),
        SD = apply(coefs, 2, sd),
        Min = apply(coefs, 2, min),
        Max = apply(coefs, 2, max),
        Sparsity = sprintf("%.2f%%", colMeans(round(coefs, 6) == 0) * 100),
        `L2-Norm` = apply(coefs, 2, function(x) sqrt(sum(x^2))),
        row.names = names
      )
      summary <- summary[order(summary$L2.Norm, decreasing = TRUE), ]
      summary[, -5] <- round(summary[, -5], 4)
      print(format(summary, justify = "right"))
    }
  }

  if (object$model$row_covariates) {
    beta <- IMR:::inv(object$Xr) %*% object$coefficients$beta
    summarize_covariates(
      t(beta), object$meta_data$names_X_vars,
      TRUE,
      object$meta_data$dimensions[2]
    )
  }
  if (object$model$col_covariates) {
    gamma <- tcrossprod(object$coefficients$gamma, IMR:::inv(object$Zr))
    summarize_covariates(
      gamma, object$meta_data$names_Z_vars,
      FALSE,
      object$meta_data$dimensions[1]
    )
  }

  if (object$model$row_intercept || object$model$col_intercept) {
    cat("\n-- Intercepts --")
    if (object$model$row_intercept) {
      coefs <- object$coefficients$beta0
      cat(sprintf("\nRow Intercepts    (n=%d) | ", length(coefs)))
      cat(sprintf(
        "Mean: %.4f | SD: %.4f | Min: %.4f | Max: %.4f\n",
        mean(coefs), sd(coefs), min(coefs), max(coefs)
      ))
    }
    if (object$model$col_intercept) {
      coefs <- object$coefficients$gamma0
      cat(sprintf("Column Intercepts (m=%d) | ", length(coefs)))
      cat(sprintf(
        "Mean: %.4f | SD: %.4f | Min: %.4f | Max: %.4f\n",
        mean(coefs), sd(coefs), min(coefs), max(coefs)
      ))
    }
  }
  if (object$model$low_rank_component) {
    cat("\n-- Latent Component --")
    cat(sprintf("\nRank (r): %d\nSingular Values:\n", length(object$coefficients$d)))
    print(object$coefficients$d)
  }

  invisible()
}


#' @export
#' @method print imr_convergence
print.imr_convergence <- function(x, ...) {
  cat("\n== IMR Convergence Parameters ==\n")

  cat(sprintf("Max Iterations: %d\n", x$maxit))
  cat(sprintf("Threshold:      %g\n", x$thresh))

  init_method <- if (x$ls_initial) "Least Squares" else "Randomized"
  cat(sprintf("Initialization: %s\n", init_method))

  # 3. Trace/Verbosity
  trace_status <- if (x$trace) "Enabled" else "Disabled"
  cat(sprintf("Trace Progress: %s\n", trace_status))

  cat("================================\n")
  invisible()
}

#' @export
#' @method coef imr_fit
coef.imr_fit <- function(x, ...) {
  return(x$coefficients)
}
#' @export
#' @method coefficients imr_fit
coefficients.imr_fit <- coef.imr_fit


#' Matrix Completion using Row and Column Means
#'
#' @description
#' A naive matrix completion method that imputes missing entries by filling them
#' with the average of their corresponding row and column means.
#'
#' @param mat A matrix object. This can be an `Incomplete` matrix, a standard
#'   sparse matrix, or a base R dense matrix. If it is not already of class
#'   `Incomplete`, it will be converted internally prior to imputation.
#'
#' @details
#' The function efficiently computes row and column means using an internal C++
#' functions, excluding missing entries. It replaces
#' each missing value at index $(i, j)$ with the arithmetic mean of the $i$-th
#' row mean and the $j$-th column mean.
#'
#' @return A dense matrix of class `Incomplete`.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Create a sample matrix with missing values (NAs)
#' mat <- matrix(c(1, NA, 3, 4, 5, NA, 7, 8, 9), nrow = 3)
#'
#' # Impute the missing values using row and column averages
#' mat_completed <- mc_with_means(mat)
#' }
mc_with_means <- function(mat) {
  # Calculate row and column means, excluding NAs
  if (!IMR::is.Incomplete(mat)) mat <- IMR::as.Incomplete(mat)
  row_means <- IMR:::row_means_cpp(mat@x, mat@i, nrow(mat), ncol(mat))
  col_means <- IMR:::col_means_cpp(mat@x, mat@p, nrow(mat), ncol(mat))
  ij <- Matrix::which(mat == 0, arr.ind = TRUE)
  mat[ij] <- (row_means[ij[, 1]] + col_means[ij[, 2]]) / 2
  mat <- Matrix::drop0(mat)
  return(mat)
}
