# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

svd_small_nc_cpp <- function(mS) {
    .Call('_IMR_svd_small_nc_cpp', PACKAGE = 'IMR', mS)
}

svd_small_nr_cpp <- function(mS) {
    .Call('_IMR_svd_small_nr_cpp', PACKAGE = 'IMR', mS)
}

